### PR TITLE
ex10 first submission

### PR DESCRIPTION
**Pull request by ray-chew**
Will add doxygen and asserts.

### CODE REVIEW

**Comment by dRehfeldt** [comment]
Hey Ray, is it really necessary to have 500+ files in the pull request?

**Comment by ray-chew** [comment]
Hi, Daniel, sorry! I included the coverage results. I'll remove them. :)

**Comment by ray-chew** [comment]
Hey Daniel, I've removed the coverage files. I hope I'm not submitting my assignment too late because of this...

**Comment by dRehfeldt** [comment]
It's ok.

**Pull request merged**
